name: Send Telemetry after Other Workflow

on:
  workflow_run:
    # Specify the workflows you want to collect telemetry.
    workflows:
      - CI CD Workflow
    # This action uses completed workflow for making traces and metrics.
    types:
      - completed

permissions:
  # Required for private repositories
  actions: read

jobs:
  send-telemetry:
    name: Send CI Telemetry
    runs-on: ubuntu-latest
    steps:
      - name: Run
        id: run
        uses: paper2/github-actions-opentelemetry@main
        env:
          OTEL_SERVICE_NAME: github-actions-opentelemetry
          OTEL_EXPORTER_OTLP_ENDPOINT: https://tempo-prod-14-prod-ap-southeast-1.grafana.net/tempo
          # Additional OTLP headers. Useful for OTLP authentication.
          # e.g.
          # New Relic: api-key=YOUR_NEWRELIC_API_KEY
          # Google Cloud Run: Authorization=Bearer <value of $(gcloud auth print-identity-token)>
          # Basic Authentication: Authorization=Basic <base64-encoded value of userid:password>
          OTEL_EXPORTER_OTLP_HEADERS:
            Authorization=Basic MTQyMTA0ODpnbGNfZXlKdklqb2lNVFl4TnpNMk1pSXNJbTRpT2lKemRHRmpheTB4TkRZNE9UUTFMV2gwTFhKbFlXUXRkR1Z0Y0c5dlpYSmxjbVZsTFhSbGJYQnZiMlZ5WlhKbFpTSXNJbXNpT2lJd09EQmtNemc1YTJkT2JWVXhlRFkwY2twak9FeEhUWEVpTENKdElqcDdJbklpT2lKd2NtOWtMV0Z3TFhOdmRYUm9aV0Z6ZEMweEluMTkK,other-config-value=value
          OTEL_RESOURCE_ATTRIBUTES: 'environment=ci,team=backend'
        with:
          # Required for collecting workflow data
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
