name: beta tag

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  tag-beta:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Fetch tags
        run: git fetch --tags origin

      - name: Create beta tag
        run: |
          BASE_TAG=${{  github.ref_name }}
          echo "Base tag $BASE_TAG exists."
