name: prod workflow sample

on:
  workflow_dispatch:

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: fdsjdjfsd
        run: |
          npm install
